/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class au_edu_uq_eresearch_biolark_ta_genia_GeniaJNI */

#ifndef _Included_au_edu_uq_eresearch_biolark_ta_genia_GeniaJNI
#define _Included_au_edu_uq_eresearch_biolark_ta_genia_GeniaJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     au_edu_uq_eresearch_biolark_ta_genia_GeniaJNI
 * Method:    initialize
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_au_edu_uq_eresearch_biolark_ta_genia_GeniaJNI_initialize
  (JNIEnv *, jobject, jstring);

/*
 * Class:     au_edu_uq_eresearch_biolark_ta_genia_GeniaJNI
 * Method:    tagSentence
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_au_edu_uq_eresearch_biolark_ta_genia_GeniaJNI_tagSentence
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
